.TL
Example
.AU
Nikita Ivanov
.SH
file.ms
.PP
.B "Lorem ipsum"
dolor sit amet, consectetur adipiscing elit.
Quisque suscipit vel quam id semper.
Fusce congue luctus mauris.
Quisque sed rutrum erat.
Curabitur erat nisi, accumsan id magna id, faucibus convallis nibh.
Donec non erat vitae augue volutpat fringilla sodales at nisl.
Donec sagittis tincidunt tellus, sit amet semper dui finibus id.
Sed a iaculis elit.
.RS
.so inc.ms
.RE
.RS
.so dir/inc.ms
.RE
