.SH
inc.ms
.PP
.I "Integer risus lorem" ,
iaculis non est auctor, dignissim condimentum magna.
Pellentesque vitae odio nibh.
In nibh ex, volutpat id suscipit id, interdum eget arcu.
Mauris dignissim sem nisi, et ullamcorper ex rhoncus in.
Praesent non felis arcu.
Etiam a ante congue, iaculis nisi faucibus, sodales nunc.
Pellentesque aliquam interdum ex.
Vestibulum varius quis nunc molestie efficitur.
.RS
.so dir/file.ms
.RE
